export const FETCH_SEARCH_PRODUCTS_START = "FETCH_SEARCH_PRODUCTS_START";
export const FETCH_SEARCH_PRODUCTS_OK = "FETCH_SEARCH_PRODUCTS_OK";
export const FETCH_SEARCH_PRODUCTS_ERROR = "FETCH_SEARCH_PRODUCTS_ERROR";
