export const ADD = "cart/ADD";
export const REMOVE_PRODUCT = "cart/REMOVE_PRODUCT";
export const FETCH_PRODUCTS_START = "cart/FETCH_PRODUCTS_START";
export const FETCH_PRODUCTS_OK = "cart/FETCH_PRODUCTS_OK";
export const FETCH_PRODUCTS_ERROR = "cart/FETCH_PRODUCTS_ERROR";

export const CHANGE_COUNT_PRODUCT = "cart/CHANGE_COUNT_PRODUCT";
