export const FETCH_PRODUCTS_START = "Products/FETCH_PRODUCTS_START";
export const FETCH_PRODUCTS_OK = "Products/FETCH_PRODUCTS_OK";
export const FETCH_PRODUCTS_ERROR = "Products/FETCH_PRODUCTS_ERROR";

export const FETCH_PRODUCT = "Products/FETCH_PRODUCT";

export const DELETE_PRODUCT_START = "Products/DELETE_PRODUCT_START";
export const DELETE_PRODUCT_OK = "Products/DELETE_PRODUCT_OK";
export const DELETE_PRODUCT_ERROR = "Products/DELETE_PRODUCT_ERROR";

export const UPDATE_PRODUCT_START = "Products/UPDATE_PRODUCT_START";
export const UPDATE_PRODUCT_OK = "Products/UPDATE_PRODUCT_OK";
export const UPDATE_PRODUCT_ERROR = "Products/UPDATE_PRODUCT_ERROR";

export const CREATE_PRODUCT_START = "Products/CREATE_PRODUCT_START";
export const CREATE_PRODUCT_OK = "Products/CREATE_PRODUCT_OK";
export const CREATE_PRODUCT_ERROR = "Products/CREATE_PRODUCT_ERROR";
